name: Python appication CI/CD

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:

    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.8
      - uses: actions/checkout@v2
      - with:
          python -m pip install --upgrade pip
          pip install unittest
      - name: Test with unittest
        run:
          python -m unittest discover -V
